---
provisioner:
  name: chef_zero
  attributes:
    instance_role: vagrant

driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.2.1
  customize:
    memsize: 1024

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[build-essential]
    attributes:
      apt:
        compile_time_update: true
      build-essential:
        compile_time: true

suites:
  - name: default
    run_list:
      - recipe[needle-skeleton]
