---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  attributes:
    instance_role: vagrant

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[skeleton::default]
    attributes:
