source 'https://rubygems.org'

gem 'berkshelf', '~> 4.3.0'
gem 'chef', '= 12.2.1'
gem 'chefspec', '~> 4.3.0'
gem 'fauxhai'
gem 'foodcritic', '~> 6.0.0'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rubocop', '~> 0.30.0'
gem 'rubocop-checkstyle_formatter'
gem 'test-kitchen', '~> 1.7.0'
